# Generated by Django 6.0.3 on 2026-03-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_file', models.FileField(upload_to='projects/')),
            ],
        ),
    ]
